"""Database tables for BHOOMI-AI.

Record.id uses the human-readable REC<date>-<seq> code (matches the demo
UI's `validationRecord.id` format) instead of an auto-increment integer, so
the same identifier is usable end to end: upload -> validation -> records
table -> audit trail.
"""
from datetime import datetime

from sqlalchemy import (
    Column, DateTime, Float, ForeignKey, Integer, String, Text,
)
from sqlalchemy.orm import relationship

from database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(80), unique=True, nullable=False, index=True)
    password_hash = Column(String(255), nullable=False)
    name = Column(String(120), nullable=False)
    role = Column(String(60), nullable=False, default="Operator")
    department = Column(String(120), nullable=False, default="Land Records")
    status = Column(String(20), nullable=False, default="Active")
    created_at = Column(DateTime, default=datetime.utcnow)


class Record(Base):
    __tablename__ = "records"

    # e.g. REC20260914-001 — generated by the pipeline, not auto-increment.
    id = Column(String(40), primary_key=True)

    # --- fields the demo dashboard table renders directly ---
    file_name = Column(String(255), nullable=False)
    state = Column(String(80), nullable=False, default="Haryana")
    status = Column(String(20), nullable=False, default="Needs Review")  # Verified | Processed | Needs Review

    # --- extracted land-record fields ---
    owner = Column(String(200))
    khasra = Column(String(80))
    khata = Column(String(80))
    village = Column(String(120))
    tehsil = Column(String(120))
    district = Column(String(120))
    area = Column(String(80))
    mutation_no = Column(String(80))

    # --- pipeline metadata ---
    confidence = Column(Integer, default=0)  # overall 0-100
    field_confidence_json = Column(Text)     # JSON: {"owner": 92, "khasra": 88, ...}
    validation_notes_json = Column(Text)     # JSON: ["Khasra format looks unusual", ...]
    source_path = Column(String(500))        # path to the stored original file
    raw_text = Column(Text)                  # OCR output, for audit / re-review

    # --- GIS: per-record geometry, always stored/served as WGS84 (EPSG:4326) ---
    latitude = Column(Float)                 # parcel centroid, decimal degrees
    longitude = Column(Float)                # parcel centroid, decimal degrees
    geometry_geojson = Column(Text)          # full parcel boundary as a GeoJSON geometry (Polygon/MultiPolygon), when imported
    geometry_source = Column(String(40))     # "shapefile" | "geojson" | "seed" | None (no import yet)
    geometry_crs_note = Column(String(255))  # e.g. "Reprojected from WGS 84 / UTM zone 43N to EPSG:4326"
    geometry_filename = Column(String(255))  # original uploaded file name, for the audit trail
    geometry_imported_at = Column(DateTime)

    uploaded_on = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    verified_by = Column(String(120))
    verified_at = Column(DateTime)

    audit_entries = relationship("AuditLog", back_populates="record", cascade="all, delete-orphan")


class AuditLog(Base):
    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    record_id = Column(String(40), ForeignKey("records.id"), nullable=False)
    action = Column(String(80), nullable=False)     # e.g. "uploaded", "auto_validated", "verified", "updated"
    actor = Column(String(120), nullable=False, default="system")
    details = Column(Text)
    timestamp = Column(DateTime, default=datetime.utcnow)

    record = relationship("Record", back_populates="audit_entries")


class Setting(Base):
    __tablename__ = "settings"

    key = Column(String(60), primary_key=True)
    value = Column(String(20), nullable=False)  # "true" / "false"
